base_dir: .
checkpoints_dir: generated/2025-05-22/reward=1.0|n=500/checkpoints
configs_dir: generated/2025-05-22/reward=1.0|n=500/configs
data:
  S: 5
  categorical: true
  dataloaders:
    train:
      batch_size: 256
    validation:
      batch_size: 256
  pad_index: 4
  preprocessing:
    filter_order:
    - reward
    filter_range_dict:
      reward:
      - -2000
      - 2000
    property_data_sampling_dict:
      reward:
        fraction: 1.0
        seed: 100
        stratify: false
        use_max_num_bins: true
    random_seed_split: 42
    torch_data_property_names:
    - reward
    validation_train_ratio: 0.2
  shape: 8
  train_num_tokens_freq_dict:
    '8': 1.0
  train_property_sigma_dict:
    reward: 0.10665700096911458
  which_dataset: sequence
denoising_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  fix_pads: false
  hidden_dim: 20000
  init_seed: 42
  num_hidden: 2
  p_dropout: 0.1
  save_name: denoising_model.pt
  stack_time: true
device: cuda
eps_ratio: 1e-9
figs_save_dir: generated/2025-05-22/reward=1.0|n=500/figs_saved
fix_pads: false
load_data: true
logging: true
logp_predictor_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  hidden_dims:
  - 1000
  init_seed: 43
  p_dropout: 0.1
  stack_time: false
  y_guide_name: logp
make_figs: true
models_load_dir: generated/2025-05-22/reward=1.0|n=500/models_saved
models_save_dir: generated/2025-05-22/reward=1.0|n=500/models_saved
num_gpus: 1
num_heavy_atoms_predictor_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  hidden_dims:
  - 1000
  init_seed: 43
  p_dropout: 0.1
  stack_time: false
  y_guide_name: num_heavy_atoms
num_rings_predictor_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  hidden_dims:
  - 1000
  init_seed: 43
  p_dropout: 0.1
  stack_time: false
  type: normal
  y_guide_name: num_rings
num_timesteps: null
outputs_dir: generated/2025-05-22/reward=1.0|n=500
reward_predictor_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  hidden_dims:
  - 1000
  init_seed: 43
  p_dropout: 0.1
  stack_time: false
  y_guide_name: reward
sampler:
  argmax_final: true
  batch_size: 128
  do_purity_sampling: false
  dt: 0.001
  grad_approx: false
  guide_temp: 0.5
  max_iterations: 100
  max_t: 0.98
  noise: 30.0
  purity_temp: 1.0
  sample_zero_time_pads: true
  seed: 30
  x1_temp: 1.0
save_figs: true
state: generation
trained_run_folder_dir: ./trained/2025-05-20/no_overrides
training:
  denoising_model:
    clip_grad: false
    lr: 0.001
    num_epochs: 2
    optimizer: Adam
    seed: 42
    warmup: 0
  logp_predictor_model:
    clip_grad: true
    lr: 0.0001
    num_epochs: 50
    optimizer: Adam
    seed: 42
    warmup: 0
  num_heavy_atoms_predictor_model:
    clip_grad: true
    lr: 0.0001
    num_epochs: 50
    optimizer: Adam
    seed: 42
    warmup: 0
  reward_predictor_model:
    clip_grad: true
    lr: 0.0001
    num_epochs: 2
    optimizer: Adam
    seed: 42
    warmup: 0
  waiting_time_predictor_model:
    clip_grad: true
    lr: 0.0001
    num_epochs: 50
    optimizer: Adam
    seed: 42
    warmup: 0
waiting_time_predictor_model:
  activation_fn:
    name: ReLU
    params: null
  eps: 1e-10
  hidden_dims:
  - 1000
  init_seed: 43
  p_dropout: 0.1
  stack_time: false
  type: normal
  y_guide_name: waiting_time
